# Generated by Django 3.2.8 on 2021-11-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweeta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.CharField(default='', max_length=700),
        ),
    ]
